"""The sketch worker — session-start flavour, once per session (M2-B).

Generates the opening line (Chinese + pinyin) and a short flavour block — the
partner's persona for this session and incidental color to draw on — from the
topic's vocab/grammar/dialogues (`kb.load_vocab_block`, deliberately *not*
`kb.load_kb_block`). It does **not** generate the goal, the slots, or
`max_turns`; those are authored in `topic.md` and parsed by `kb.py`
(`docs/SCENARIOS.md`). This is the one call the M2 design calls out as
de-risked: the criteria that must not drift never pass through a model at
all — not generated by one, and not read by one either — so there is nothing
here to get wrong in a way that breaks a session. `situation`/`goal` still
reach the prompt, just via `render_sketch_prompt`, not the KB block.

Unlike `workers.conversation`, this is a single call per session, not a
per-turn hot path — there is no `cache_control` breakpoint to place here. The
*result* is what gets frozen by the caller and ridden through the cached
prefix on every turn after this one.
"""
from typing import Optional

import anthropic
from anthropic import AsyncAnthropic

from backend import config, kb
from backend.models import SketchResult
from backend.prompts import render_sketch_prompt

_client: Optional[AsyncAnthropic] = None


class SketchError(Exception):
    """Claude refused, or returned output we could not parse into our schema."""


def _get_client() -> AsyncAnthropic:
    """Lazily build a shared async client — same construction as the
    conversation worker's, so the one-off call gets the same retry/timeout
    posture as the hot path (`workers.conversation._get_client`)."""
    global _client
    if _client is None:
        _client = AsyncAnthropic(
            api_key=config.ANTHROPIC_API_KEY,
            max_retries=config.CLAUDE_MAX_RETRIES,
        )
    return _client


def build_request(*, kb_block: str, scenario: kb.Scenario) -> dict:
    """Assemble the one-off `messages.parse` kwargs for a session's flavour.

    No `cache_control` breakpoint: this call happens exactly once per session,
    so there is nothing here for a second call to read back from cache. The KB
    block rides as a user message rather than the system prompt for the same
    reason — the caching machinery in `workers.conversation` doesn't apply.
    """
    return {
        "model": config.CONVERSATION_MODEL,
        "max_tokens": 1024,
        # Same reasoning as the conversation worker: a short structured reply
        # has no use for adaptive thinking, and `max_tokens` caps both.
        "thinking": {"type": "disabled"},
        "system": [{"type": "text", "text": render_sketch_prompt(scenario)}],
        "messages": [{"role": "user", "content": kb_block}],
        "output_format": SketchResult,
    }


async def generate(
    topic_id: str, scenario: kb.Scenario, *, client: Optional[AsyncAnthropic] = None
) -> SketchResult:
    """Generate one session's opening line + flavour from its topic KB.

    Takes the scenario rather than loading it — the caller (`orchestrator.
    start_session`) already loaded the `Topic` to build the `ScenarioCard` and
    check it has a scenario at all, and `kb.load_topic` isn't cached, so a
    second call here would be a real duplicate disk read + frontmatter parse
    per session start for no benefit. Taking `Scenario` rather than `Topic`
    also makes "no scenario" structurally impossible to hit here: there is no
    `None` to check.

    Raises `kb.KbError` for an unknown topic, `SketchError` on a refusal,
    timeout, or unparseable reply — the same failure shapes as
    `workers.conversation.respond`.
    """
    # Vocab/grammar/dialogues only — never `load_kb_block`, which also carries
    # the authored slots. The sketch worker gets `situation`/`goal` through the
    # system prompt instead; it must never see the slot graph at all.
    kb_block = kb.load_vocab_block(topic_id)

    client = client or _get_client()
    request = build_request(kb_block=kb_block, scenario=scenario)

    try:
        response = await client.messages.parse(
            **request, timeout=config.CLAUDE_TIMEOUT_S
        )
    except anthropic.APITimeoutError as exc:
        raise SketchError(
            f"sketch worker timed out after {config.CLAUDE_TIMEOUT_S:g}s"
        ) from exc

    if getattr(response, "stop_reason", None) == "refusal":
        raise SketchError("sketch worker refused the session")
    result = response.parsed_output
    if result is None:
        raise SketchError("sketch worker returned unparseable output")
    return result
