"""Contact test for the generated flavour block — does it really cache?

The sketch worker's *structural* eval moved onto cassettes in A0.6
(`tests/test_worker_behavior.py`). What stayed here is the claim a recording
cannot make: a real second call read a real cache. Issue #30's acceptance bar
was that swapping the hardcoded `SKETCH_STUB` for generated bytes changed *who
generates the bytes*, not the caching contract — and only the API can say so.

Excluded from the default run (`pytest.ini addopts=-m "not live"`); invoke with
`pytest -m live` and a real `ANTHROPIC_API_KEY`. The scheduled live job runs it
weekly (`.github/workflows/live.yml`).
"""
import pytest

from anthropic import AsyncAnthropic

from backend import config, kb
from backend.workers import conversation, sketch

pytestmark = pytest.mark.live


def _client():
    if not config.ANTHROPIC_API_KEY:
        pytest.skip("ANTHROPIC_API_KEY not configured")
    return AsyncAnthropic(api_key=config.ANTHROPIC_API_KEY)


async def test_live_generated_flavour_caches_across_turns():
    """The frozen flavour block is byte-identical across every turn of a
    session: generate it once, hand the exact same string to two turns, and
    the second must read the cache (issue #30 acceptance)."""
    client = _client()
    # `load_converser_block`, never `load_kb_block` — the partner is goal-blind
    # under V2, and the prefix under test has to be the shipped one.
    kb_block = kb.load_converser_block("greetings")

    session = await sketch.generate(
        "greetings", kb.load_scenario("greetings"), client=client
    )

    _r1, _a1, _rd1, usage1 = await conversation.respond(
        kb_block=kb_block, sketch=session.sketch, dialogue=[], user_text="你好",
        forgiveness_level=config.FORGIVENESS_LEVEL_DEFAULT, client=client,
    )
    assert (
        usage1.cache_creation_input_tokens > 0 or usage1.cache_read_input_tokens > 0
    ), "prefix did not cache — too small?"

    _r2, _a2, _rd2, usage2 = await conversation.respond(
        kb_block=kb_block, sketch=session.sketch,
        dialogue=[
            {"role": "user", "zh": "你好"},
            {"role": "partner", "zh": _r1.zh},
        ],
        user_text="我叫小明",
        forgiveness_level=config.FORGIVENESS_LEVEL_DEFAULT, client=client,
    )
    assert usage2.cache_read_input_tokens > 0, "cache miss — generated flavour isn't byte-stable?"
